AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout:
  Enabled: true

Metrics:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 18

Style:
  Enabled: true

Style/Documentation:
  Enabled: false

Naming:
  Enabled: true
